sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5.7.0'
before_install:
  - npm i -g npm@3.6.0`
before_script:
  - npm prune
script:
  - npm run build
  - npm run coverage-generate
  - npm run coverage-check
after_success:
  - npm run semantic-release
  - npm run coverage-report
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
